source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

pod 'JSQSystemSoundPlayer-Swift', :git => 'https://github.com/s-faychatelard/JSQSystemSoundPlayer-Swift.git', :tag => '1.0'
